apiVersion: apps/v1
kind: Deployment
metadata:
  name: horizon-deployment
  labels:
    app: horizon
spec:
  selector:
    matchLabels:
      app: horizon
  replicas: 1
  template:
    metadata:
      labels:
        app: horizon
    spec:
      containers:
      - name: horizon
        image: lanitgithub/horizon-web:dev
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: "500m"
          requests:
            memory: 256Mi
            cpu: "160m"
# Доступ будет по http://127.0.0.1:30000/  (или http://10.126.145.36:30000/)
# TODO Переделать на ingress https://habr.com/ru/company/southbridge/blog/358824/
---
apiVersion: v1
kind: Service
metadata:
  name: horizon
spec:
  selector:
    app: horizon
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort
