# Generated by Django 2.2.13 on 2020-06-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='source_files/%d.%m.%y')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_storage.Test')),
            ],
        ),
        migrations.CreateModel(
            name='JMRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField()),
                ('elapsed', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('responseCode', models.PositiveSmallIntegerField()),
                ('success', models.BooleanField()),
                ('grpThreads', models.PositiveSmallIntegerField()),
                ('SampleCount', models.PositiveSmallIntegerField()),
                ('ErrorCount', models.PositiveSmallIntegerField()),
                ('Hostname', models.CharField(max_length=30)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.SourceFile')),
            ],
        ),
    ]
