# Generated by Django 2.2.13 on 2020-06-05 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_horizon_agent', models.BooleanField(verbose_name='Является агентом')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
            ],
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='test',
            name='artefacts',
            field=models.URLField(blank=True, verbose_name='Ссылка на артефакты'),
        ),
        migrations.AddField(
            model_name='test',
            name='result',
            field=models.TextField(blank=True, verbose_name='Краткие результаты'),
        ),
        migrations.AddField(
            model_name='test',
            name='task',
            field=models.URLField(blank=True, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(blank=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(blank=True, verbose_name='Дата начала'),
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('description_url', models.URLField(blank=True, help_text='wiki', verbose_name='Ссылка на описание')),
                ('documents_url', models.URLField(blank=True, help_text='Ссылка на sharepoint (МНТ и Отчеты)', verbose_name='Документы')),
                ('scripts_url', models.URLField(blank=True, help_text='GitLab', verbose_name='Ссылка на скрипты')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TestPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например, "Рост", "Удержание", "Снижение"', max_length=30, verbose_name='Наименование')),
                ('start_time', models.DateTimeField(blank=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='Время окончания')),
                ('testplan', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_storage.Test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='load_stations',
            field=models.ManyToManyField(help_text='Указываем только станции с которых подавалась нагрузка.', to='test_storage.LoadStation', verbose_name='Список станций'),
        ),
        migrations.AddField(
            model_name='test',
            name='testplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_storage.TestPlan'),
        ),
    ]
