# Generated by Django 2.2.13 on 2020-06-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0002_auto_20200605_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadstation',
            name='hostname',
            field=models.CharField(default='test', max_length=30, verbose_name='Hostname'),
            preserve_default=False,
        ),
    ]
