# Generated by Django 2.2.13 on 2020-06-18 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_storage', '0003_loadstation_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(default='temp', max_length=10, unique=True, verbose_name='Алиас'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тест инженер проводивший тест'),
            preserve_default=False,
        ),
    ]
