# Generated by Django 2.2.13 on 2020-06-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0007_auto_20200618_1818'),
    ]

    atomic = False

    operations = [
        migrations.RenameModel(
            old_name='RawLogs',
            new_name='RawLogsFile',
        ),
    ]
