# Generated by Django 2.2.13 on 2020-06-18 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0008_auto_20200618_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='JMeterRawLogsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='raw_logs/%d.%m.%y')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_storage.Test')),
            ],
            options={
                'verbose_name': 'Файл логов JMeter',
                'verbose_name_plural': 'Файлы логов JMeter',
            },
        ),
        migrations.AlterField(
            model_name='jmrequest',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.JMeterRawLogsFile'),
        ),
        migrations.DeleteModel(
            name='RawLogsFile',
        ),
    ]
