# Generated by Django 2.2.13 on 2020-06-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0009_auto_20200618_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AlterModelOptions(
            name='loadstation',
            options={'verbose_name': 'Нагрузочная станция', 'verbose_name_plural': 'Нагрузочные станции'},
        ),
        migrations.AlterModelOptions(
            name='testphase',
            options={'verbose_name': 'Фаза теста', 'verbose_name_plural': 'Фазы теста'},
        ),
        migrations.AlterModelOptions(
            name='testplan',
            options={'verbose_name': 'Тест-план', 'verbose_name_plural': 'Тест-планы'},
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='jmeterrawlogsfile',
            name='test',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='test_storage.Test'),
            preserve_default=False,
        ),
    ]
