# Generated by Django 2.2.13 on 2020-06-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0010_auto_20200618_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='artefacts',
            new_name='artifacts',
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
