# Generated by Django 2.2.13 on 2020-06-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0011_auto_20200618_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='system_version',
            field=models.TextField(default='', verbose_name='Версия системы'),
            preserve_default=False,
        ),
    ]
