# Generated by Django 2.2.13 on 2020-06-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0012_test_system_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='errors_pct',
            field=models.FloatField(default=None, verbose_name='% ошибок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='response_time_avg',
            field=models.FloatField(default=None, verbose_name='Среднее время отклика, сек'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='rps_avg',
            field=models.FloatField(default=None, verbose_name='Avg RPS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='successful',
            field=models.BooleanField(blank=True, null=True, verbose_name='Успешность теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='testplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.TestPlan'),
        ),
    ]
