# Generated by Django 2.2.13 on 2020-06-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0013_auto_20200619_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='errors_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='% ошибок'),
        ),
        migrations.AlterField(
            model_name='test',
            name='response_time_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее время отклика, сек'),
        ),
        migrations.AlterField(
            model_name='test',
            name='rps_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='Avg RPS'),
        ),
    ]
