# Generated by Django 2.2.13 on 2020-06-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0015_auto_20200619_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='errors_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='% ошибок'),
        ),
        migrations.AddField(
            model_name='test',
            name='response_time_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее время отклика, сек'),
        ),
        migrations.AddField(
            model_name='test',
            name='rps_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='Avg RPS'),
        ),
        migrations.AddField(
            model_name='test',
            name='successful',
            field=models.BooleanField(blank=True, null=True, verbose_name='Успешность теста'),
        ),
    ]
