# Generated by Django 2.2.13 on 2020-06-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0017_auto_20200619_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
