# Generated by Django 2.2.13 on 2020-06-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('test_storage', '0018_auto_20200619_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Customer',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Заказачик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='account',
            new_name='customer',
        ),
    ]
