# Generated by Django 2.2.13 on 2020-06-24 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0019_auto_20200624_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadstation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_storage.Customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_storage.Customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='test',
            name='load_stations',
            field=models.ManyToManyField(help_text='Указываем только станции с которых подавалась нагрузка.', limit_choices_to={'hostname': 'nload01'}, to='test_storage.LoadStation', verbose_name='Список станций'),
        ),
    ]
