# Generated by Django 2.2.13 on 2020-07-01 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0020_auto_20200624_1243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JMRequest',
            new_name='JmeterRequest',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='jmeterrawlogsfile',
            options={'verbose_name': 'Файлы логов JMeter', 'verbose_name_plural': 'Файлы логов JMeter'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='description_url',
        ),
        migrations.AddField(
            model_name='project',
            name='description_url',
            field=models.URLField(blank=True, help_text='wiki', verbose_name='Ссылка на описание'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='test_type',
            field=models.CharField(choices=[('STB', 'Тест стабильности'), ('MAX', 'Поиск максимума'), ('SIN', 'Синтетический тест')], default='MAX', max_length=3),
        ),
        migrations.AlterField(
            model_name='jmeterrequest',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.JmeterRawLogsFile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(max_length=20, unique=True, verbose_name='Алиас'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='test',
            name='load_stations',
            field=models.ManyToManyField(help_text='Указываем только станции с которых подавалась нагрузка.', to='test_storage.LoadStation', verbose_name='Список станций'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='documents_url',
            field=models.URLField(blank=True, help_text='Ссылка на sharepoint (МНТ и Отчеты)', max_length=1000, verbose_name='Документы'),
        ),
    ]
