# Generated by Django 2.2.13 on 2020-06-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0020_auto_20200624_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterField(
            model_name='test',
            name='load_stations',
            field=models.ManyToManyField(help_text='Указываем только станции с которых подавалась нагрузка.', to='test_storage.LoadStation', verbose_name='Список станций'),
        ),
    ]
