# Generated by Django 3.0.9 on 2020-08-03 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0021_auto_20200701_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='JmeterSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_url', models.URLField(verbose_name='Ссылка на скрипт в gitlab')),
            ],
        ),
        migrations.AlterField(
            model_name='jmeterrequest',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.JmeterRawLogsFile'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='test_type',
            field=models.CharField(choices=[('STB', 'Тест стабильности'), ('MAX', 'Поиск максимума'), ('SIN', 'Синтетический тест'), ('STR', 'Стрессовое тестирование'), ('VOL', 'Объемное тестирование'), ('SMK', 'Дымовое тестирование'), ('SCA', 'Тестирование масштабируемости')], default='MAX', max_length=3),
        ),
    ]
