# Generated by Django 3.0.9 on 2020-08-03 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0022_auto_20200803_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jmetersource',
            options={'verbose_name': 'Скрипт НТ', 'verbose_name_plural': 'Скрипты НТ'},
        ),
        migrations.RenameField(
            model_name='jmetersource',
            old_name='description_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='jmeterrequest',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.JmeterRawLogsFile'),
        ),
    ]
