# Generated by Django 3.0.9 on 2020-08-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0023_auto_20200803_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmetersource',
            name='token',
            field=models.CharField(blank=True, help_text='Токен сгенерировать можно по ссылке: https://gitlab.dks.lanit.ru/profile/personal_access_tokensНеобходимые права(scopes): "read_repository"', max_length=30, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='jmeterrequest',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.JmeterRawLogsFile'),
        ),
    ]
