# Generated by Django 3.0.9 on 2020-08-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0024_auto_20200803_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplan',
            name='scripts_url',
        ),
        migrations.AddField(
            model_name='testplan',
            name='jmeter_source',
            field=models.ForeignKey(blank=True, help_text='GitLab', null=True, on_delete=django.db.models.deletion.CASCADE, to='test_storage.JmeterSource'),
        ),
        migrations.AlterField(
            model_name='jmeterrequest',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.JmeterRawLogsFile'),
        ),
    ]
