# Generated by Django 3.0.9 on 2020-08-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0027_auto_20200805_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmeterrequest',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.JmeterRawLogsFile'),
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на артефакты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.Test')),
            ],
        ),
    ]
