# Generated by Django 3.0.9 on 2020-08-11 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0029_auto_20200811_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmeterrequest',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.JmeterRawLogsFile'),
        ),
    ]
