# Generated by Django 3.0.9 on 2020-08-12 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0030_auto_20200811_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadstation',
            options={'ordering': ['customer', 'hostname'], 'verbose_name': 'Нагрузочная станция', 'verbose_name_plural': 'Нагрузочные станции'},
        ),
        migrations.AddField(
            model_name='loadstation',
            name='cpu_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество ядер, штук'),
        ),
        migrations.AddField(
            model_name='loadstation',
            name='disk_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Объём диска, Гб'),
        ),
        migrations.AddField(
            model_name='loadstation',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='loadstation',
            name='memory_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Объём памяти, Гб'),
        ),
        migrations.AddField(
            model_name='loadstation',
            name='os',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='loadstation',
            name='soft',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Программное обеспечение'),
        ),
        migrations.AlterField(
            model_name='jmeterrequest',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.JmeterRawLogsFile'),
        ),
        migrations.AlterField(
            model_name='loadstation',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='test',
            name='artifacts',
            field=models.URLField(blank=True, help_text='Это поле удалим в следующей ревизии', verbose_name='DEPRECATED! Ссылка на артефакты'),
        ),
    ]
