# Generated by Django 3.0.9 on 2020-08-12 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0031_auto_20200812_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmeterrequest',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.JmeterRawLogsFile'),
        ),
        migrations.AlterField(
            model_name='test',
            name='artifacts',
            field=models.URLField(blank=True, editable=False, help_text='Это поле удалим в следующей ревизии', verbose_name='DEPRECATED! Ссылка на артефакты'),
        ),
    ]
