# Generated by Django 3.0.8 on 2020-08-19 11:22

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0033_auto_20200819_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmeterrequest',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.JmeterRawLogsFile'),
        ),
        migrations.AlterField(
            model_name='test',
            name='state',
            field=django_fsm.FSMField(choices=[('J', 'Running JMeter master'), ('C', 'Completed')], default='J', max_length=50),
        ),
    ]
