# Generated by Django 3.0.8 on 2020-08-19 13:30

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('test_storage', '0034_auto_20200819_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pod_log',
            field=models.TextField(blank=True, verbose_name='Лог автоматического запуска.'),
        ),
        migrations.AlterField(
            model_name='jmeterrequest',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_storage.JmeterRawLogsFile'),
        ),
        migrations.AlterField(
            model_name='test',
            name='state',
            field=django_fsm.FSMField(choices=[('P', 'Подготовка теста инженером'), ('J', 'Running JMeter master'), ('C', 'Completed')], default='P', max_length=50),
        ),
    ]
