GET http://localhost:8000/api/jmeter_logs/
Accept: application/json
Authorization: Token 94d69b182249bc9bb358d88c10143015713fbb32

###


POST http://localhost:8000/api/jmeter_logs/
Authorization: Token 94d69b182249bc9bb358d88c10143015713fbb32
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="test_id"

1
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="empty_jmeter_log.csv"

< ./test_resources/empty_jmeter_log.csv

--WebAppBoundary--

###


POST http://localhost:8000/api/jmeter_logs/
Authorization: Token 94d69b182249bc9bb358d88c10143015713fbb32
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="test_id"

projectName_20200805_132959
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="empty_jmeter_log.csv"

< ./test_resources/empty_jmeter_log.csv

--WebAppBoundary--
###
